#!/bin/bash -l

set -e

[[ -f /etc/entrypoint ]] && . /etc/entrypoint
[[ -f /etc/default/$APP ]] && . /etc/default/$APP

: readonly ${PUBLIC_IPV4:=$(get-ipv4)}
: readonly ${PUBLIC_FQDN:=$(env hostname -f)}
: readonly ${DOMAIN_NAME:=$(dnsdomainname)}

# accepts: debug info notice warn error critical alert
: readonly ${KAMAILIO_LOG_LEVEL:=info}
: readonly ${KAMAILIO_LOG_COLOR:=true}

: readonly ${KAMAILIO_MY_HOSTNAME:=$PUBLIC_FQDN}
: readonly ${KAMAILIO_MY_IP_ADDRESS:=$PUBLIC_IPV4}
: readonly ${KAMAILIO_MY_WEBSOCKET_DOMAIN:=$DOMAIN_NAME}

: readonly ${RABBITMQ_HOSTS:=rabbitmq}

: readonly ${RABBITMQ_USER:=guest}
: readonly ${RABBITMQ_PASS:=guest}

: declare -ir ${KAMAILIO_SHM_MEMORY:=256}
: declare -ir ${KAMAILIO_PKG_MEMORY:=12}
: declare -ir ${KAMAILIO_CHILD_PROC:=$(kamailio::get-child-procs)}
: declare -ir ${KAMAILIO_MTU:=$(net::get-mtu)}

: readonly ${KAMAILIO_ENABLE_ROLES:=websockets,message}

readonly LOG_LEVEL=$(kamailio::get-loglevel $KAMAILIO_LOG_LEVEL)
readonly AMQP_HOSTS=($(kazoo::build-amqp-uris "$RABBITMQ_HOSTS" 'kazoo'))


pushd /etc/kamailio
    log::m-info "Setting log level to: $LOG_LEVEL ..."
    sed -i "s/<LOG_LEVEL>/$LOG_LEVEL/" local.cfg

    if (( $KAMAILIO_MTU != 1500 )); then
        log::m-info "Changing MTU to $MTU"
        sed -i "/udp4_raw_mtu/s/\b[[:digit:]]\+$/$MTU/" local.cfg
    fi

    log::m-info "Rewriting local.cfg ..."
    sed -i "s/<MY_HOSTNAME>/$KAMAILIO_MY_HOSTNAME/" local.cfg
    sed -i "s/<MY_IP_ADDRESS>/$KAMAILIO_MY_IP_ADDRESS/" $_
    sed -i "s|<MY_AMQP_URL>|${AMQP_HOSTS[0]}|" $_
    sed -i "s/<MY_WEBSOCKET_DOMAIN>/$KAMAILIO_MY_WEBSOCKET_DOMAIN/" $_

    if (( ${#AMQP_HOSTS[@]} > 1 )); then
        log::m-info "Enabling secondary amqp server:  ${AMQP_HOSTS[1]} ..."
        sed -i "s/<MY_AMQP_SECONDARY_URL>/${AMQP_HOSTS[1]}/" local.cfg
    fi

    if (( ${#AMQP_HOSTS[@]} > 2 )); then
        log::m-info "Enabling tertiary amqp server: ${AMQP_HOSTS[2]} ..."
        sed -i "s/<MY_AMQP_TERTIARY_URL>/${AMQP_HOSTS[1]}/" local.cfg
    fi

    log::m-info "Enabling roles: ${KAMAILIO_ENABLE_ROLES} in local.cfg ..."
    if [[ -n $KAMAILIO_ENABLE_ROLES ]]; then
        for role in ${KAMAILIO_ENABLE_ROLES//,/ }; do
            sed -i "/${role^^}_ROLE/s/# # //" local.cfg
        done
    fi
    cat local.cfg
    popd


if [ ! -f /etc/kamailio/db/kazoo.db ]; then
    KazooDB -init /etc/kamailio/kazoodb.sql /etc/kamailio/db/kazoo.db
    chown kamailio:kamailio /etc/kamailio/db/kazoo.db
fi


log::m-info "Setting ulimits ..."
set-limits 'kamailio'

if linux::cap::is-enabled 'sys_nice'; then
    log::m-info "Enabling real-time priority settings ..."
    sed -i '/Global Parameters/a \
real_time = 7 \
rt_prio = 70 \
rt_policy = 2 \
rt_timer1_prio = 70 \
rt_timer1_policy = 2 \
rt_timer2_prio = 70 \
rt_timer2_policy = 2' /etc/kamailio/default.cfg
fi

for cap in net_raw ipc_lock; do
    if linux::cap::is-disabled $cap; then
        linux::cap::show-warning $cap
    fi
done


log::m-info "Ensuring Permissions ..."
chown -R $USER:$USER /etc/kamailio /volumes/kamailio
fixattrs


log::m-info "Building arguments ..."
CMD_ARGS=("-DD")
[[ ! -z $KAMAILIO_SHM_MEMORY ]] && \
    CMD_ARGS+=("-m $KAMAILIO_SHM_MEMORY")
[[ ! -z $KAMAILIO_PKG_MEMORY ]] && \
    CMD_ARGS+=("-M $KAMAILIO_PKG_MEMORY")
[[ ! -z $KAMAILIO_CHILD_PROC ]] && \
    CMD_ARGS+=("-n $KAMAILIO_CHILD_PROC")
[[ $KAMAILIO_LOG_COLOR = true ]] && \
    CMD_ARGS+=("-e")
set -- ${CMD_ARGS[@]}


log::m-info "Starting $APP ..."
cd ~
    exec kamailio "$@"
